[toolchain]
channel = "nightly-2024-12-31"
components = ["rustfmt", "rust-src", "clippy", "llvm-tools", "rust-analyzer"]
targets = [
    "aarch64-unknown-none",
    "riscv64gc-unknown-none-elf",
    "x86_64-unknown-none",
]
