cargo-features = ["per-package-target"]

[package]
name = "riscv64"
version = "0.1.0"
edition = "2021"
default-target = "riscv64imac-unknown-none-elf"

[dependencies]
port = { path = "../port" }
bitflags = "2.3.3"
bit_field = "0.10.2"

[features]
opensbi = []
